// other
const separatorSymobl = ",";

// ---- Formating function

// add seprator for thousands

// RECIEVES a number in STRING format
// RETURNS formated numbers in STRING format
export function thousandsSeparator(x, separator = separatorSymobl) {
	x = x.split(".");
	let decimalPart = x[1] ? x[1] : "";
	return (
		x[0].replace(/\B(?=(\d{3})+(?!\d))/g, separator) +
		(decimalPart && ".") +
		decimalPart
	);
}

// format api (custom function)
export function FormatAPI(apiData) {
	apiData = JSON.parse(apiData.replace(/\\/gi, ""));

	return apiData;
}

// get month name

// getMonthName[$month + 1]
// RETURNS month name in STRING format
export const GetMonthName = [
	"Jan",
	"Feb",
	"Mar",
	"Apr",
	"May",
	"Jun",
	"Jul",
	"Aug",
	"Sep",
	"Oct",
	"Nov",
	"Dec",
];

// edit how the data from the api will visualize
// order is preserved

// props
// private: specifies if the data type is private. musst be included after (access)
// title: the title for the metric
// value: metric value/s
// popup: text for the info icon
// prefix: prefix for the value (applies only in numbers section)
// group: grouping type for graphs - 'week', 'month' (used for formating)

export function getObjectFromAPI(api, access) {
	const apiJson = api ? JSON.parse(api.Data.Data) : {};

	// console.log(apiJson);

	api = apiJson;
	return {
		title: [
			"VCOIN Transacted",
			api.VCoinTransacted,
			"The sum of all VCOIN transactions",
		],
		numbers: [
			[
				{
					private: false,
					title: "Total supply",
					value: api.TotalSupply,
					popup: "All VCOIN minted to date",
				},
				{
					private: false,
					title: "Circulating supply",
					value: api.CirculatingSupply,
					popup: "VCOIN available for purchase and deployed in market",
				},
				{
					private: false,
					title: "VCOIN In Market",
					value: api.VCoinInMarketValue,
					popup:
						"The number of VCOIN in market (circulating VCOIN minus VCOIN held by IMVU)",
				},
			],
			[
				{
					private: false,
					title: "VCOIN Market Value",
					value: api.VCoinMarketValue,
					popup: "The value of all VCOINs in US Dollars",
					prefix: "$",
				},
				{
					private: false,
					title: "VCOIN Circulating Value",
					value: api.VCoinCirculatingValue,
					popup: "The circulating supply of VCOIN in US Dollars",
					prefix: "$",
				},
				{
					private: false,
					title: "Total VCOIN Wallets",
					value: api.TotalVCoinUsers,
					popup: "The number of users who transacted, held or purchased VCOINs",
				},
			],
			[
				{
					private: false,
					title: "Peer to Peer Transacted VCOINs",
					value: api.UserToUserVCoin,
					popup: "The amount of VCOINs that have been transacted between users",
				},
				{
					private: false,
					title: "Days Since Launch",
					value: api.DaysSinceLaunch,
					popup:
						"Number of days since the VCOIN token officially launched on IMVU",
				},
			],
			access &&
				api.FeesGeneratedVCoin && [
					{
						private: true,
						title: "VCOIN fees generated",
						value: api.FeesGeneratedVCoin,
						popup: "Number of VCOIN generated by IMVU as fees",
					},
					{
						private: true,
						title: "VCOIN outside of Uphold",
						value: api.OutsideUpholdVCoin,
						popup: "Number of VCOINS outside of the IMVU-Uphold platform",
					},
				],
			access &&
				api.PurchasedVCoin && [
					{
						private: true,
						title: "VCOIN Purchased",
						value: api.PurchasedVCoin,
						popup: "Sum of all VCOIN purchased by users",
					},
					{
						private: true,
						title: "Number of VCOIN Purchase Transactions",
						value: api.NumberOfPurchaseTransactions,
						popup: "Number of individual VCOIN purchase transactions",
					},
				],
		],
		graphs: [
			[
				{
					private: false,
					title: "VCOIN New Wallets",
					value: api.NewWalletsPerWeek,
					group: "week",
					popup:
						"The number of wallets that are using VCOIN for the first time.",
				},
				{
					private: false,
					title: "VCOIN Transacted",
					value: api.AllTransactionsPerWeek,
					group: "week",
					popup: "The amount of VCOIN that was transacted",
				},
				{
					private: false,
					title: "Number Of Peer to Peer Transactions",
					value: api.NumberOfUserToUserTransactionsGroupedPerWeek,
					group: "week",
					popup: "The number of transactions between users involving VCOIN",
				},
				{
					private: false,
					title: "Peer to Peer Transacted VCOINs",
					value: api.UserToUserTransactionsPerWeek,
					group: "week",
					popup:
						"The amount of VCOINs that have been transacted between users. ",
				},
			],
			access &&
				api.ActiveWalletsPerMonth && [
					{
						private: true,
						title: "Monthly Active VCOIN wallets",
						value: api.ActiveWalletsPerWeek,
						group: "week",
						popup: "Monthly Active VCOIN wallets",
					},
					{
						private: true,
						title: "VCOIN Fees Graph",
						value: api.FeesTransactionPerWeek,
						group: "week",
						popup: "VCOIN Fees Graph",
					},
					{
						private: true,
						title: "VCOIN Purchased",
						value: api.PurchaseTransactionsPerWeek,
						group: "week",
						popup: "VCOIN Purchased",
					},
					{
						private: true,
						title: "Number of VCOIN Purchased",
						value: api.NumberOfPurchaseTransactionsGroupedPerWeek,
						group: "week",
						popup: "Number of VCOIN Purchased",
					},
					// {
					//     private: true,
					//     title: 'VCOIN Outside of Uphold',
					//     value: api.EthereumTransactionPerWeek
					// },
				],
		],
	};
}
